language: generic
sudo: required
services: 
 - docker

before_install: 
 - docker build -t jtangs/docker-react -f Dockerfile.dev .

script: 
 - docker run -e CI=true jtangs/docker-react npm run test

deploy: 
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "docker-react"
 environment: "Dockerreact-env"
 bucket_name: "elasticbeanstalk-us-east-2-352439219008"
 bucket_path: "docker-react"
 on: 
  branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

